name: Warm-up repo
description: Prepares Node and Yarn dependencies

inputs:
  playwright-deps:
    default: ""
    description: "List of browsers separated by space, e.g. 'chrome firefox'"
    required: false

runs:
  using: composite

  steps:
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: 20 ## aligned with Node version on Vercel
        # cache: yarn ## Currently disabled because of frequent timeouts

    - name: Install WASM tools
      uses: taiki-e/install-action@f1390fd0d8205ae79e5e57b1d1e300dceeb4163e # v2.49.44
      with:
        tool: wasm-pack@0.12.1

    - name: Install yarn dependencies
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
      env:
        HUSKY: 0
      with:
        max_attempts: 3
        timeout_minutes: 10
        shell: bash
        command: |
          export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD="${{ inputs.playwright-deps == '' }}"
          yarn install --frozen-lockfile --prefer-offline

    - name: npx playwright install
      if: ${{ inputs.playwright-deps != '' }}
      uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
      with:
        max_attempts: 3
        timeout_minutes: 10
        shell: bash
        command: npx playwright install --with-deps ${{ inputs.playwright-deps }}
